---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: j7s-os-app-deployment
  labels:
    app: j7s-os-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: j7s-os-app
  template:
    metadata:
      labels:
        app: j7s-os-app
    spec:
      containers:
      - name: j7s-os-app
        image: 192.168.1.128:8443/j7s-os-deploy:latest
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: j7s-os-app-service
spec:
  selector:
    app: j7s-os-app
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: j7s-os-app-ingress
spec:
  rules:
  - host: j7s-os.internal.jpace121.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: j7s-os-app-service
            port:
              number: 3001