---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: tekton-host
spec:
  hostname: "tekton.internal.jpace121.net"
  requestPolicy:
    insecure:
      action: Route
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: http-listener
spec:
  port: 8080
  protocol: HTTP
  securityModel: INSECURE
  hostBinding:
    namespace:
      from: SELF