apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: dev-contain-rpm
spec:
  pipelineRef:
    name: dev-contain-pipeline
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-credentials
    secret:
      secretName: git-credentials
  - name: deploy-credentials
    secret:
      secretName: deploy-credentials
  params:
  - name: branch
    value: "packaging/fedora"
  - name: deploy
    value: "true"