apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: with-custom-container-2
spec:
  pipelineRef:
    name: cat-git-repo
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-credentials
    secret:
      secretName: git-credentials
  params:
  - name: repo-url
    value: ssh://git@git.jpace121.net:2222/jimmy/tekton-test.git
