apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: j7s-os-test-
spec:
  pipelineRef:
    name: j7s-os-pipeline
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
  - name: git-credentials
    secret:
      secretName: git-credentials
  params:
  - name: make-image-name
    value: cs9-qemu-minimal-ostree.x86_64.repo
  - name: short-name
    value: j7s-os
  serviceAccountName: internal-kubectl