apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: k8s-action-test-
spec:
  serviceAccountName: internal-kubectl
  taskRef:
    name: kubernetes-actions
  params:
    - name: script
      value: |
        kubectl version
        kubectl get deploy