# A pipeline to build and deploy my fork of the debian packaging for ostree.
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ostree-package-pipeline
spec:
  description: "Package fork of ostree."
  params:
  - name: deploy
    type: string
    description: "'true' if we should deploy the image using ansible."
  workspaces:
  - name: shared-data
    description: Shared data.
  - name: git-credentials
    description: tekton git credentials
  - name: deploy-credentials
    description: tekton credentials to deployment server
  tasks:
  - name: fetch-repo
    workspaces:
    - name: output
      workspace: shared-data
    - name: ssh-directory
      workspace: git-credentials
    params:
    - name: url
      value: ssh://git.jpace121.net:2222/packaging/ostree
    - name: branch
      value: jamesp/latest
    taskRef:
      name: j7s-git-clone
  - name: build
    runAfter: ["fetch-repo"]
    workspaces:
    - name: source
      workspace: shared-data
    - name: ssh-directory
      workspace: deploy-credentials
    params:
    - name: deploy
      value: $(params.deploy)
    - name: ansible-file-path
      value: ./j7s-build-files
    taskRef:
      name: j7s-ansible-build