apiVersion: batch/v1
kind: Job
metadata:
  name: test-trigger-check
spec:
  template:
    spec:
      containers:
      - name: test-trigger-check
        image: 192.168.1.128:8443/curl:latest
        command: ["bash"]
        args:
          - "-c"
          - >-
            curl -X POST http://el-test-pipeline-listener.default.svc.cluster.local:8080 -H 'Content-Type: application/json' -d '{}'
      restartPolicy: Never
  backoffLimit: 0